/**
 * Comprehensive list of 100+ popular AI tools
 * This ensures the website is fully populated on first deployment
 */

import type { PricingDetails } from '@/types/tool';

export interface ToolSeed {
  name: string;
  description: string;
  category: string;
  website_url: string;
  logo_url?: string;
  pricing_free: boolean;
  pricing_tier: string;
  pricing_details: PricingDetails;
  features: string[];
  use_cases: string[];
  tags: string[];
}

export const comprehensiveTools: ToolSeed[] = [
  // Text AI - Major Players
  {
    name: 'ChatGPT',
    description: 'Advanced AI chatbot by OpenAI for conversations, writing, coding, and problem-solving with GPT-4',
    category: 'Text AI',
    website_url: 'https://chat.openai.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'GPT-3.5 available' },
    features: ['GPT-4 access', 'Code interpreter', 'Plugins', 'Image understanding', 'Multi-language'],
    use_cases: ['Writing assistance', 'Coding help', 'Research', 'Content creation', 'Data analysis'],
    tags: ['chatbot', 'gpt', 'openai', 'writing', 'coding'],
  },
  {
    name: 'Claude',
    description: 'Anthropic\'s AI assistant with long context windows, focused on helpful and safe responses',
    category: 'Text AI',
    website_url: 'https://claude.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited messages' },
    features: ['200K context', 'Document upload', 'Code generation', 'Writing assistance', 'Analysis'],
    use_cases: ['Document analysis', 'Long-form writing', 'Research', 'Coding', 'Summarization'],
    tags: ['anthropic', 'assistant', 'writing', 'analysis'],
  },
  {
    name: 'Perplexity',
    description: 'AI-powered search engine that provides real-time answers with citations and sources',
    category: 'Text AI',
    website_url: 'https://perplexity.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited queries' },
    features: ['Real-time search', 'Citations', 'Source links', 'Multi-modal', 'Pro search'],
    use_cases: ['Research', 'Fact-checking', 'Information gathering', 'News updates'],
    tags: ['search', 'research', 'ai', 'citations'],
  },
  {
    name: 'Gemini',
    description: 'Google\'s multimodal AI model that understands text, images, audio, and video',
    category: 'Text AI',
    website_url: 'https://gemini.google.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Available' },
    features: ['Multimodal', 'Image understanding', 'Code generation', 'Google integration', 'Extreme context'],
    use_cases: ['Multimodal tasks', 'Google Workspace', 'Research', 'Image analysis'],
    tags: ['google', 'multimodal', 'assistant', 'workspace'],
  },
  {
    name: 'Pi by Inflection',
    description: 'Personal AI assistant designed for empathetic and helpful conversations',
    category: 'Text AI',
    website_url: 'https://inflection.ai/pi',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Conversational AI', 'Personal assistant', 'Empathetic responses', 'Mobile app'],
    use_cases: ['Personal assistant', 'Conversations', 'Support', 'Companionship'],
    tags: ['assistant', 'personal', 'chat', 'free'],
  },
  {
    name: 'Character.AI',
    description: 'Chat with AI characters, celebrities, and custom personalities',
    category: 'Text AI',
    website_url: 'https://character.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Available' },
    features: ['Character creation', 'Voice chat', 'Group chats', 'Custom personalities'],
    use_cases: ['Entertainment', 'Roleplay', 'Learning', 'Creative writing'],
    tags: ['chatbot', 'characters', 'entertainment', 'roleplay'],
  },
  {
    name: 'Jasper',
    description: 'AI writing assistant for marketing, blogs, and business content',
    category: 'Text AI',
    website_url: 'https://jasper.ai',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$49', annual: '$468' },
    features: ['Content templates', 'Brand voice', 'SEO optimization', 'Multi-language', 'Team collaboration'],
    use_cases: ['Blog writing', 'Marketing copy', 'Social media', 'Email campaigns'],
    tags: ['writing', 'marketing', 'content', 'seo'],
  },
  {
    name: 'Copy.ai',
    description: 'AI copywriting tool for marketing, sales, and social media content',
    category: 'Text AI',
    website_url: 'https://copy.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$49', free_tier: 'Limited credits' },
    features: ['Copy templates', 'Blog writing', 'Social media', 'Email copy', 'Product descriptions'],
    use_cases: ['Marketing copy', 'Social posts', 'Email marketing', 'Product descriptions'],
    tags: ['copywriting', 'marketing', 'content', 'social-media'],
  },
  {
    name: 'Grammarly',
    description: 'AI-powered writing assistant for grammar, style, and clarity improvements',
    category: 'Text AI',
    website_url: 'https://grammarly.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Basic checks' },
    features: ['Grammar check', 'Style suggestions', 'Tone detection', 'Plagiarism check', 'Browser extension'],
    use_cases: ['Writing improvement', 'Email', 'Documents', 'Academic writing'],
    tags: ['grammar', 'writing', 'editing', 'productivity'],
  },
  {
    name: 'Notion AI',
    description: 'AI writing assistant integrated into Notion for notes, docs, and wikis',
    category: 'Text AI',
    website_url: 'https://notion.so/product/ai',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Note generation', 'Summarization', 'Translation', 'Brainstorming', 'Notion integration'],
    use_cases: ['Note-taking', 'Documentation', 'Knowledge base', 'Project management'],
    tags: ['notion', 'writing', 'productivity', 'notes'],
  },
  {
    name: 'Writesonic',
    description: 'AI content generator for blogs, ads, and marketing materials',
    category: 'Text AI',
    website_url: 'https://writesonic.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$19', free_tier: 'Limited words' },
    features: ['Article writer', 'Ad copy', 'Product descriptions', 'Landing pages', 'SEO content'],
    use_cases: ['Blog writing', 'Marketing', 'E-commerce', 'SEO content'],
    tags: ['writing', 'marketing', 'seo', 'content'],
  },
  {
    name: 'Rytr',
    description: 'AI writing assistant for creating high-quality content in seconds',
    category: 'Text AI',
    website_url: 'https://rytr.me',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: '5K characters/month' },
    features: ['30+ use cases', '20+ tones', '30+ languages', 'SEO optimization', 'Plagiarism check'],
    use_cases: ['Blog posts', 'Social media', 'Emails', 'Product descriptions'],
    tags: ['writing', 'content', 'seo', 'multilingual'],
  },

  // Image AI
  {
    name: 'Midjourney',
    description: 'AI art generator known for stunning, artistic images with unique styles',
    category: 'Image AI',
    website_url: 'https://midjourney.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$10', annual: '$96' },
    features: ['Art generation', 'Style control', 'High resolution', 'Community gallery', 'Discord integration'],
    use_cases: ['Digital art', 'Concept art', 'Illustrations', 'Creative projects', 'Marketing visuals'],
    tags: ['art', 'generation', 'creative', 'design'],
  },
  {
    name: 'DALL-E 3',
    description: 'OpenAI\'s advanced image generation model with improved quality and safety',
    category: 'Image AI',
    website_url: 'https://openai.com/dall-e-3',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: 'Pay per image', free_tier: 'Via ChatGPT Plus' },
    features: ['Text-to-image', 'High quality', 'Safe generation', 'Multiple styles', 'ChatGPT integration'],
    use_cases: ['Image creation', 'Design', 'Marketing materials', 'Concept visualization', 'Art'],
    tags: ['openai', 'image-generation', 'art', 'design'],
  },
  {
    name: 'Stable Diffusion',
    description: 'Open-source AI image generation model with extensive customization options',
    category: 'Image AI',
    website_url: 'https://stability.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Free (self-hosted)', free_tier: 'Available' },
    features: ['Open source', 'Custom models', 'ControlNet', 'Inpainting', 'Image-to-image'],
    use_cases: ['Art generation', 'Research', 'Custom projects', 'Commercial use'],
    tags: ['open-source', 'generation', 'art', 'customizable'],
  },
  {
    name: 'Leonardo.ai',
    description: 'AI image generation platform with advanced controls and model training',
    category: 'Image AI',
    website_url: 'https://leonardo.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: '150 images/day' },
    features: ['Image generation', 'Model training', 'Image editing', '3D textures', 'AI canvas'],
    use_cases: ['Game assets', 'Marketing visuals', 'Art creation', '3D textures'],
    tags: ['generation', 'gaming', 'art', '3d'],
  },
  {
    name: 'Runway ML',
    description: 'Creative suite with AI tools for image, video, and audio generation',
    category: 'Image AI',
    website_url: 'https://runwayml.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited credits' },
    features: ['Image generation', 'Video editing', 'Inpainting', 'Motion tracking', 'Green screen'],
    use_cases: ['Video editing', 'Image editing', 'Creative projects', 'Film production'],
    tags: ['video', 'editing', 'generation', 'creative'],
  },
  {
    name: 'Adobe Firefly',
    description: 'Adobe\'s generative AI for images, vectors, and creative content',
    category: 'Image AI',
    website_url: 'https://firefly.adobe.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$5', free_tier: 'Limited generations' },
    features: ['Text-to-image', 'Vector generation', 'Text effects', 'Adobe integration', 'Commercial safe'],
    use_cases: ['Design', 'Marketing', 'Creative projects', 'Adobe workflows'],
    tags: ['adobe', 'design', 'generation', 'commercial'],
  },
  {
    name: 'Canva AI',
    description: 'AI-powered design tools integrated into Canva for easy content creation',
    category: 'Image AI',
    website_url: 'https://canva.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$13', free_tier: 'Limited features' },
    features: ['Magic Design', 'Text-to-image', 'Background removal', 'Image enhancement', 'Template generation'],
    use_cases: ['Social media', 'Presentations', 'Marketing materials', 'Design'],
    tags: ['design', 'canva', 'social-media', 'templates'],
  },
  {
    name: 'Figma AI',
    description: 'AI features in Figma for design assistance and automation',
    category: 'Image AI',
    website_url: 'https://figma.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited' },
    features: ['Design suggestions', 'Auto-layout', 'Component generation', 'Prototyping', 'Collaboration'],
    use_cases: ['UI/UX design', 'Prototyping', 'Design systems', 'Collaboration'],
    tags: ['design', 'ui', 'ux', 'prototyping'],
  },

  // Video AI
  {
    name: 'Runway Gen-2',
    description: 'Text-to-video AI for generating videos from text prompts',
    category: 'Video AI',
    website_url: 'https://runwayml.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited seconds' },
    features: ['Text-to-video', 'Image-to-video', 'Video editing', 'Motion graphics', 'Green screen'],
    use_cases: ['Video creation', 'Marketing videos', 'Creative projects', 'Film production'],
    tags: ['video', 'generation', 'editing', 'creative'],
  },
  {
    name: 'Pika Labs',
    description: 'AI video generation platform for creating short videos from text or images',
    category: 'Video AI',
    website_url: 'https://pika.art',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Text-to-video', 'Image-to-video', 'Video extension', 'Style transfer', 'Animation'],
    use_cases: ['Short videos', 'Social media', 'Animations', 'Creative projects'],
    tags: ['video', 'generation', 'animation', 'social-media'],
  },
  {
    name: 'Synthesia',
    description: 'AI video generation with virtual avatars for presentations and training',
    category: 'Video AI',
    website_url: 'https://synthesia.io',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$30', annual: '$300' },
    features: ['AI avatars', '140+ languages', 'Voice cloning', 'Template library', 'Custom avatars'],
    use_cases: ['Training videos', 'Presentations', 'Marketing', 'E-learning'],
    tags: ['video', 'avatars', 'presentations', 'training'],
  },
  {
    name: 'Descript',
    description: 'AI-powered video and audio editing with transcription and overdub',
    category: 'Video AI',
    website_url: 'https://descript.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited hours' },
    features: ['Transcription', 'Overdub', 'Video editing', 'Screen recording', 'Collaboration'],
    use_cases: ['Video editing', 'Podcasts', 'Tutorials', 'Content creation'],
    tags: ['video', 'editing', 'audio', 'transcription'],
  },
  {
    name: 'Luma AI',
    description: 'AI-powered 3D capture and rendering from photos and videos',
    category: 'Video AI',
    website_url: 'https://lumalabs.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited captures' },
    features: ['3D capture', 'NeRF rendering', 'Video to 3D', 'AR/VR support', 'Export options'],
    use_cases: ['3D modeling', 'AR/VR', 'Product visualization', 'Architecture'],
    tags: ['3d', 'ar', 'vr', 'rendering'],
  },

  // Code AI
  {
    name: 'GitHub Copilot',
    description: 'AI pair programmer that suggests code as you type',
    category: 'Code AI',
    website_url: 'https://github.com/features/copilot',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$10', free_tier: 'For students' },
    features: ['Code completion', 'Multi-language', 'Context awareness', 'IDE integration', 'Chat'],
    use_cases: ['Coding', 'Debugging', 'Learning', 'Productivity'],
    tags: ['coding', 'github', 'ide', 'productivity'],
  },
  {
    name: 'Cursor',
    description: 'AI-powered code editor with advanced code generation and editing',
    category: 'Code AI',
    website_url: 'https://cursor.sh',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited requests' },
    features: ['Code generation', 'Chat', 'Multi-file editing', 'Codebase understanding', 'Refactoring'],
    use_cases: ['Coding', 'Refactoring', 'Debugging', 'Learning'],
    tags: ['coding', 'editor', 'ide', 'productivity'],
  },
  {
    name: 'Replit',
    description: 'Cloud-based IDE with AI coding assistant for rapid development',
    category: 'Code AI',
    website_url: 'https://replit.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Available' },
    features: ['Cloud IDE', 'AI assistant', 'Multi-language', 'Deployment', 'Collaboration'],
    use_cases: ['Coding', 'Learning', 'Prototyping', 'Collaboration'],
    tags: ['coding', 'ide', 'cloud', 'education'],
  },
  {
    name: 'Tabnine',
    description: 'AI code completion that learns from your codebase',
    category: 'Code AI',
    website_url: 'https://tabnine.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Basic completion' },
    features: ['Code completion', 'Multi-language', 'Private model', 'IDE integration', 'Team features'],
    use_cases: ['Coding', 'Productivity', 'Team collaboration'],
    tags: ['coding', 'completion', 'ide', 'productivity'],
  },
  {
    name: 'Codeium',
    description: 'Free AI code completion and chat for developers',
    category: 'Code AI',
    website_url: 'https://codeium.com',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Unlimited' },
    features: ['Code completion', 'Chat', 'Multi-language', 'IDE integration', 'Free tier'],
    use_cases: ['Coding', 'Learning', 'Productivity'],
    tags: ['coding', 'free', 'completion', 'ide'],
  },
  {
    name: 'Sourcegraph Cody',
    description: 'AI coding assistant that understands your entire codebase',
    category: 'Code AI',
    website_url: 'https://sourcegraph.com/cody',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Codebase search', 'Code generation', 'Explanations', 'Refactoring', 'Multi-repo'],
    use_cases: ['Code understanding', 'Refactoring', 'Onboarding', 'Documentation'],
    tags: ['coding', 'codebase', 'search', 'productivity'],
  },
  {
    name: 'Hugging Face',
    description: 'Platform for AI models, datasets, and spaces with inference API',
    category: 'Code AI',
    website_url: 'https://huggingface.co',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Model hosting', 'Datasets', 'Spaces', 'Inference API', 'Transformers'],
    use_cases: ['Model development', 'Research', 'Deployment', 'Experimentation'],
    tags: ['models', 'ml', 'open-source', 'api'],
  },
  {
    name: 'Replicate',
    description: 'Platform to run AI models with simple API calls',
    category: 'Code AI',
    website_url: 'https://replicate.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Pay per use', free_tier: 'Limited' },
    features: ['Model API', 'Fast inference', 'Auto-scaling', 'Many models', 'Easy integration'],
    use_cases: ['Model deployment', 'Prototyping', 'Production apps', 'Experimentation'],
    tags: ['api', 'models', 'deployment', 'ml'],
  },

  // Audio AI
  {
    name: 'ElevenLabs',
    description: 'AI voice generation and cloning for natural-sounding speech',
    category: 'Audio AI',
    website_url: 'https://elevenlabs.io',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$5', free_tier: '10K characters/month' },
    features: ['Voice cloning', 'Text-to-speech', 'Voice library', 'Multi-language', 'Emotion control'],
    use_cases: ['Audiobooks', 'Podcasts', 'Voiceovers', 'Accessibility'],
    tags: ['voice', 'tts', 'audio', 'cloning'],
  },
  {
    name: 'Mubert',
    description: 'AI music generation for background music and soundtracks',
    category: 'Audio AI',
    website_url: 'https://mubert.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$14', free_tier: 'Limited' },
    features: ['Music generation', 'Royalty-free', 'Multiple genres', 'API access', 'Custom tracks'],
    use_cases: ['Background music', 'Content creation', 'Streaming', 'Commercial use'],
    tags: ['music', 'generation', 'audio', 'royalty-free'],
  },
  {
    name: 'Suno AI',
    description: 'AI music generation for creating complete songs with vocals',
    category: 'Audio AI',
    website_url: 'https://suno.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited songs' },
    features: ['Song generation', 'Vocals', 'Multiple genres', 'Lyrics generation', 'Instrumental'],
    use_cases: ['Music creation', 'Content creation', 'Prototyping', 'Entertainment'],
    tags: ['music', 'generation', 'songs', 'creative'],
  },
  {
    name: 'Adobe Podcast',
    description: 'AI-powered audio editing and enhancement for podcasts',
    category: 'Audio AI',
    website_url: 'https://podcast.adobe.com',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Audio enhancement', 'Noise removal', 'Mic check', 'Transcription', 'Free'],
    use_cases: ['Podcasts', 'Audio editing', 'Quality improvement'],
    tags: ['audio', 'podcast', 'editing', 'free'],
  },
  {
    name: 'Lovo AI',
    description: 'AI voice generation platform with 500+ voices in 100+ languages',
    category: 'Audio AI',
    website_url: 'https://lovo.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$19', free_tier: 'Limited' },
    features: ['Voice library', 'Voice cloning', 'Text-to-speech', 'Multi-language', 'Emotions'],
    use_cases: ['Voiceovers', 'Audiobooks', 'Content creation', 'Accessibility'],
    tags: ['voice', 'tts', 'audio', 'multilingual'],
  },

  // Productivity AI
  {
    name: 'Notion',
    description: 'All-in-one workspace with AI features for notes, docs, and project management',
    category: 'Productivity AI',
    website_url: 'https://notion.so',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited blocks' },
    features: ['AI writing', 'Notes', 'Databases', 'Templates', 'Collaboration'],
    use_cases: ['Note-taking', 'Project management', 'Documentation', 'Knowledge base'],
    tags: ['productivity', 'notes', 'project-management', 'collaboration'],
  },
  {
    name: 'Mem',
    description: 'AI-powered note-taking app that organizes and connects your ideas',
    category: 'Productivity AI',
    website_url: 'https://mem.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Auto-organization', 'Smart search', 'Connections', 'AI writing', 'Calendar integration'],
    use_cases: ['Note-taking', 'Knowledge management', 'Idea organization'],
    tags: ['notes', 'productivity', 'organization', 'knowledge'],
  },
  {
    name: 'Otter.ai',
    description: 'AI transcription and note-taking for meetings and conversations',
    category: 'Productivity AI',
    website_url: 'https://otter.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: '600 minutes/month' },
    features: ['Live transcription', 'Meeting notes', 'Speaker identification', 'Search', 'Integrations'],
    use_cases: ['Meeting notes', 'Interviews', 'Lectures', 'Accessibility'],
    tags: ['transcription', 'meetings', 'notes', 'productivity'],
  },
  {
    name: 'Fireflies',
    description: 'AI meeting assistant that records, transcribes, and summarizes meetings',
    category: 'Productivity AI',
    website_url: 'https://fireflies.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited storage' },
    features: ['Meeting recording', 'Transcription', 'AI summaries', 'Search', 'Integrations'],
    use_cases: ['Meeting notes', 'Team collaboration', 'Follow-ups', 'Documentation'],
    tags: ['meetings', 'transcription', 'productivity', 'collaboration'],
  },
  {
    name: 'Motion',
    description: 'AI calendar and task manager that automatically schedules your day',
    category: 'Productivity AI',
    website_url: 'https://motion.app',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$19', annual: '$190' },
    features: ['Auto-scheduling', 'Task management', 'Calendar sync', 'Time blocking', 'Priority management'],
    use_cases: ['Time management', 'Task scheduling', 'Productivity', 'Calendar management'],
    tags: ['calendar', 'scheduling', 'productivity', 'tasks'],
  },
  {
    name: 'Reclaim AI',
    description: 'AI calendar assistant that optimizes your schedule and protects focus time',
    category: 'Productivity AI',
    website_url: 'https://reclaim.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$8', free_tier: 'Limited' },
    features: ['Smart scheduling', 'Focus time', 'Habits', 'Task blocking', 'Calendar sync'],
    use_cases: ['Time management', 'Focus time', 'Work-life balance', 'Scheduling'],
    tags: ['calendar', 'productivity', 'scheduling', 'focus'],
  },
  {
    name: 'Tavily',
    description: 'AI research assistant that searches and synthesizes information from the web',
    category: 'Productivity AI',
    website_url: 'https://tavily.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited queries' },
    features: ['Web search', 'Information synthesis', 'API access', 'Real-time data', 'Citations'],
    use_cases: ['Research', 'Information gathering', 'Fact-checking', 'Content creation'],
    tags: ['research', 'search', 'productivity', 'api'],
  },
  {
    name: 'Zapier',
    description: 'Automation platform with AI features for connecting apps and workflows',
    category: 'Productivity AI',
    website_url: 'https://zapier.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: '5 zaps' },
    features: ['Workflow automation', 'AI actions', 'App integrations', 'Webhooks', 'Scheduling'],
    use_cases: ['Automation', 'Workflows', 'Integration', 'Productivity'],
    tags: ['automation', 'workflows', 'integration', 'productivity'],
  },
  {
    name: 'Make (Integromat)',
    description: 'Visual automation platform with AI features for complex workflows',
    category: 'Productivity AI',
    website_url: 'https://make.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: '1,000 operations' },
    features: ['Visual workflows', 'AI modules', 'Data transformation', 'Error handling', 'Scheduling'],
    use_cases: ['Automation', 'Data processing', 'Workflows', 'Integration'],
    tags: ['automation', 'workflows', 'visual', 'productivity'],
  },
  {
    name: 'Bardeen',
    description: 'AI automation tool that automates repetitive tasks in your browser',
    category: 'Productivity AI',
    website_url: 'https://bardeen.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited automations' },
    features: ['Browser automation', 'AI actions', 'Workflow builder', 'Integrations', 'Shortcuts'],
    use_cases: ['Browser automation', 'Repetitive tasks', 'Data entry', 'Productivity'],
    tags: ['automation', 'browser', 'productivity', 'workflows'],
  },

  // Additional Text AI Tools
  {
    name: 'You.com',
    description: 'AI search engine with conversational interface and real-time information',
    category: 'Text AI',
    website_url: 'https://you.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Available' },
    features: ['AI search', 'Chat interface', 'Real-time data', 'Citations', 'Apps integration'],
    use_cases: ['Research', 'Information gathering', 'Fact-checking', 'Quick answers'],
    tags: ['search', 'ai', 'research', 'chat'],
  },
  {
    name: 'Poe',
    description: 'Platform to chat with multiple AI models including GPT-4, Claude, and more',
    category: 'Text AI',
    website_url: 'https://poe.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited messages' },
    features: ['Multiple AI models', 'Chat interface', 'Bot creation', 'Mobile app', 'Fast responses'],
    use_cases: ['AI conversations', 'Model comparison', 'Custom bots', 'Experimentation'],
    tags: ['chat', 'ai-models', 'platform', 'multi-model'],
  },
  {
    name: 'HuggingChat',
    description: 'Open-source AI chat interface powered by Hugging Face models',
    category: 'Text AI',
    website_url: 'https://huggingface.co/chat',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Open source', 'Multiple models', 'Free', 'Custom models', 'API access'],
    use_cases: ['AI chat', 'Experimentation', 'Development', 'Research'],
    tags: ['open-source', 'chat', 'free', 'huggingface'],
  },
  {
    name: 'Poe by Quora',
    description: 'AI chat platform with access to multiple AI models in one place',
    category: 'Text AI',
    website_url: 'https://poe.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['Multiple models', 'Bot creation', 'Fast responses', 'Mobile app'],
    use_cases: ['AI chat', 'Model testing', 'Custom assistants'],
    tags: ['chat', 'platform', 'multi-model'],
  },
  {
    name: 'Cohere',
    description: 'Enterprise AI platform for text generation, classification, and embeddings',
    category: 'Text AI',
    website_url: 'https://cohere.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Custom', free_tier: 'Limited API calls' },
    features: ['Text generation', 'Classification', 'Embeddings', 'Rerank', 'Enterprise'],
    use_cases: ['Enterprise AI', 'Content generation', 'Classification', 'Search'],
    tags: ['enterprise', 'api', 'nlp', 'business'],
  },
  {
    name: 'Anthropic Claude API',
    description: 'API access to Claude AI models for developers and businesses',
    category: 'Text AI',
    website_url: 'https://anthropic.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: 'Pay per token', free_tier: 'No' },
    features: ['API access', 'Long context', 'Enterprise', 'Custom models', 'High quality'],
    use_cases: ['API integration', 'Enterprise apps', 'Custom solutions'],
    tags: ['api', 'enterprise', 'claude', 'developer'],
  },
  {
    name: 'OpenAI API',
    description: 'API access to GPT-4, GPT-3.5, and other OpenAI models',
    category: 'Text AI',
    website_url: 'https://platform.openai.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: 'Pay per token', free_tier: 'No' },
    features: ['GPT-4 access', 'Multiple models', 'Fine-tuning', 'Embeddings', 'Enterprise'],
    use_cases: ['API integration', 'Custom apps', 'Enterprise solutions'],
    tags: ['api', 'gpt', 'openai', 'developer'],
  },
  {
    name: 'Writer',
    description: 'AI writing assistant for teams with brand voice and style guides',
    category: 'Text AI',
    website_url: 'https://writer.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$18', annual: '$180' },
    features: ['Team collaboration', 'Brand voice', 'Style guides', 'Content templates', 'SEO'],
    use_cases: ['Team writing', 'Brand consistency', 'Content creation', 'Marketing'],
    tags: ['writing', 'teams', 'brand', 'content'],
  },
  {
    name: 'Sudowrite',
    description: 'AI writing tool for creative writing, fiction, and storytelling',
    category: 'Text AI',
    website_url: 'https://sudowrite.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$19', annual: '$190' },
    features: ['Creative writing', 'Story generation', 'Character development', 'Plot ideas', 'Dialogue'],
    use_cases: ['Fiction writing', 'Creative projects', 'Storytelling', 'Novels'],
    tags: ['writing', 'creative', 'fiction', 'stories'],
  },
  {
    name: 'NovelAI',
    description: 'AI-powered creative writing assistant for stories and novels',
    category: 'Text AI',
    website_url: 'https://novelai.net',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Story writing', 'Character AI', 'Image generation', 'Unlimited context', 'Custom models'],
    use_cases: ['Creative writing', 'Stories', 'Novels', 'Roleplay'],
    tags: ['writing', 'creative', 'stories', 'novels'],
  },

  // Additional Image AI Tools
  {
    name: 'Stable Diffusion XL',
    description: 'Latest Stable Diffusion model for high-quality image generation',
    category: 'Image AI',
    website_url: 'https://stability.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Free (self-hosted)', free_tier: 'Available' },
    features: ['High quality', '1024x1024', 'Open source', 'Customizable', 'Commercial use'],
    use_cases: ['Art generation', 'Commercial projects', 'Custom models'],
    tags: ['generation', 'art', 'open-source', 'high-quality'],
  },
  {
    name: 'Flux',
    description: 'Advanced AI image generation model with exceptional quality',
    category: 'Image AI',
    website_url: 'https://blackforestlabs.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['High quality', 'Fast generation', 'Multiple styles', 'Commercial use'],
    use_cases: ['Professional art', 'Commercial projects', 'Marketing'],
    tags: ['generation', 'art', 'quality', 'commercial'],
  },
  {
    name: 'Ideogram',
    description: 'AI image generator with excellent text rendering capabilities',
    category: 'Image AI',
    website_url: 'https://ideogram.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$8', free_tier: 'Limited' },
    features: ['Text in images', 'High quality', 'Multiple styles', 'Fast generation'],
    use_cases: ['Text-based images', 'Posters', 'Marketing', 'Design'],
    tags: ['generation', 'text', 'design', 'marketing'],
  },
  {
    name: 'Playground AI',
    description: 'AI image generation platform with advanced controls and filters',
    category: 'Image AI',
    website_url: 'https://playgroundai.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$15', free_tier: '1,000 images/day' },
    features: ['Image generation', 'Filters', 'Inpainting', 'Outpainting', 'ControlNet'],
    use_cases: ['Art creation', 'Image editing', 'Design', 'Creative projects'],
    tags: ['generation', 'editing', 'art', 'design'],
  },
  {
    name: 'Craiyon',
    description: 'Free AI image generator (formerly DALL-E mini)',
    category: 'Image AI',
    website_url: 'https://craiyon.com',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Free generation', 'Multiple images', 'Simple interface', 'No signup'],
    use_cases: ['Quick images', 'Experimentation', 'Learning'],
    tags: ['generation', 'free', 'simple', 'art'],
  },
  {
    name: 'NightCafe',
    description: 'AI art generator with multiple models and style options',
    category: 'Image AI',
    website_url: 'https://nightcafe.studio',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: '5 credits/day' },
    features: ['Multiple models', 'Style transfer', 'Art community', 'High resolution', 'Prints'],
    use_cases: ['Art creation', 'Style experiments', 'Community sharing'],
    tags: ['generation', 'art', 'community', 'styles'],
  },
  {
    name: 'Artbreeder',
    description: 'AI art generator for creating and breeding artistic images',
    category: 'Image AI',
    website_url: 'https://artbreeder.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: 'Limited' },
    features: ['Image breeding', 'Style mixing', 'Portraits', 'Landscapes', 'Community'],
    use_cases: ['Art creation', 'Style exploration', 'Portrait generation'],
    tags: ['generation', 'art', 'breeding', 'community'],
  },
  {
    name: 'Lexica',
    description: 'AI image search and generation platform with prompt library',
    category: 'Image AI',
    website_url: 'https://lexica.art',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Image search', 'Prompt library', 'Generation', 'High quality', 'Community'],
    use_cases: ['Prompt discovery', 'Image generation', 'Inspiration'],
    tags: ['generation', 'search', 'prompts', 'community'],
  },
  {
    name: 'DreamStudio',
    description: 'Official Stable Diffusion interface by Stability AI',
    category: 'Image AI',
    website_url: 'https://dreamstudio.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Pay per image', free_tier: '25 free credits' },
    features: ['Stable Diffusion', 'High quality', 'Fast generation', 'API access'],
    use_cases: ['Professional art', 'Commercial use', 'API integration'],
    tags: ['generation', 'stable-diffusion', 'api', 'professional'],
  },
  {
    name: 'Fotor AI',
    description: 'AI image generator and editor with multiple creative tools',
    category: 'Image AI',
    website_url: 'https://fotor.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: 'Limited' },
    features: ['Image generation', 'Photo editing', 'Background removal', 'Templates', 'Design'],
    use_cases: ['Image editing', 'Design', 'Marketing materials'],
    tags: ['generation', 'editing', 'design', 'photos'],
  },

  // Additional Video AI Tools
  {
    name: 'Synthesia',
    description: 'AI video generation with virtual avatars for presentations',
    category: 'Video AI',
    website_url: 'https://synthesia.io',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$30', annual: '$300' },
    features: ['AI avatars', '140+ languages', 'Voice cloning', 'Template library', 'Custom avatars'],
    use_cases: ['Training videos', 'Presentations', 'Marketing', 'E-learning'],
    tags: ['video', 'avatars', 'presentations', 'training'],
  },
  {
    name: 'HeyGen',
    description: 'AI video generation platform with talking avatars',
    category: 'Video AI',
    website_url: 'https://heygen.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$24', free_tier: 'Limited' },
    features: ['Talking avatars', 'Voice cloning', 'Multi-language', 'Custom avatars', 'Templates'],
    use_cases: ['Video creation', 'Presentations', 'Marketing', 'Training'],
    tags: ['video', 'avatars', 'presentations', 'marketing'],
  },
  {
    name: 'D-ID',
    description: 'AI platform for creating talking head videos from photos',
    category: 'Video AI',
    website_url: 'https://d-id.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$6', free_tier: 'Limited credits' },
    features: ['Talking photos', 'Video generation', 'API access', 'Custom voices', 'Animations'],
    use_cases: ['Video creation', 'Animations', 'Presentations', 'Marketing'],
    tags: ['video', 'animation', 'talking-heads', 'api'],
  },
  {
    name: 'InVideo AI',
    description: 'AI-powered video editor for creating professional videos',
    category: 'Video AI',
    website_url: 'https://invideo.io',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$15', free_tier: 'Limited exports' },
    features: ['Video editing', 'AI scripts', 'Templates', 'Stock media', 'Text-to-video'],
    use_cases: ['Video creation', 'Marketing videos', 'Social media', 'Content'],
    tags: ['video', 'editing', 'templates', 'marketing'],
  },
  {
    name: 'Pictory',
    description: 'AI video generator that creates videos from scripts and articles',
    category: 'Video AI',
    website_url: 'https://pictory.ai',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$19', annual: '$190' },
    features: ['Script to video', 'Article to video', 'Auto-editing', 'Stock media', 'Voiceovers'],
    use_cases: ['Content videos', 'Blog to video', 'Marketing', 'Social media'],
    tags: ['video', 'content', 'automation', 'marketing'],
  },
  {
    name: 'Fliki',
    description: 'AI video generator that creates videos from text with voiceovers',
    category: 'Video AI',
    website_url: 'https://fliki.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$21', free_tier: '5 minutes/month' },
    features: ['Text to video', 'AI voiceovers', 'Stock media', 'Templates', 'Multi-language'],
    use_cases: ['Video creation', 'Content videos', 'Social media', 'Marketing'],
    tags: ['video', 'text-to-video', 'voiceovers', 'content'],
  },
  {
    name: 'Colossyan',
    description: 'AI video generator with realistic AI presenters',
    category: 'Video AI',
    website_url: 'https://colossyan.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$19', free_tier: 'Limited' },
    features: ['AI presenters', 'Multi-language', 'Templates', 'Auto-translation', 'Custom avatars'],
    use_cases: ['Training videos', 'Presentations', 'E-learning', 'Corporate'],
    tags: ['video', 'presenters', 'training', 'corporate'],
  },
  {
    name: 'Steve AI',
    description: 'AI video generator that creates videos from text, images, or audio',
    category: 'Video AI',
    website_url: 'https://steve.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$15', free_tier: 'Limited' },
    features: ['Text to video', 'Image to video', 'Audio to video', 'Templates', 'Stock media'],
    use_cases: ['Video creation', 'Content', 'Marketing', 'Social media'],
    tags: ['video', 'generation', 'content', 'marketing'],
  },

  // Additional Code AI Tools
  {
    name: 'Amazon CodeWhisperer',
    description: 'AI coding companion by Amazon for code suggestions',
    category: 'Code AI',
    website_url: 'https://aws.amazon.com/codewhisperer',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Code suggestions', 'Multi-language', 'Security scanning', 'IDE integration', 'Free'],
    use_cases: ['Coding', 'Security', 'Productivity', 'Learning'],
    tags: ['coding', 'aws', 'free', 'security'],
  },
  {
    name: 'CodeT5',
    description: 'Open-source code generation model by Salesforce',
    category: 'Code AI',
    website_url: 'https://github.com/salesforce/CodeT5',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Open source' },
    features: ['Code generation', 'Open source', 'Multiple languages', 'Fine-tuning'],
    use_cases: ['Research', 'Custom models', 'Experimentation'],
    tags: ['coding', 'open-source', 'research', 'models'],
  },
  {
    name: 'Windsurf',
    description: 'AI-powered code editor with advanced features',
    category: 'Code AI',
    website_url: 'https://codeium.com/windsurf',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['Code editor', 'AI assistant', 'Multi-file editing', 'Codebase understanding'],
    use_cases: ['Coding', 'Development', 'Productivity'],
    tags: ['coding', 'editor', 'ide', 'productivity'],
  },
  {
    name: 'Continue',
    description: 'Open-source AI coding assistant for VS Code',
    category: 'Code AI',
    website_url: 'https://continue.dev',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Open source' },
    features: ['VS Code extension', 'Open source', 'Multiple models', 'Customizable'],
    use_cases: ['Coding', 'VS Code', 'Development'],
    tags: ['coding', 'vscode', 'open-source', 'extension'],
  },
  {
    name: 'Aider',
    description: 'AI coding assistant that works with your codebase',
    category: 'Code AI',
    website_url: 'https://aider.chat',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['Code editing', 'Git integration', 'Multi-file changes', 'CLI tool'],
    use_cases: ['Coding', 'Refactoring', 'Development'],
    tags: ['coding', 'cli', 'git', 'productivity'],
  },
  {
    name: 'Bito AI',
    description: 'AI coding assistant for IDEs with code generation and explanation',
    category: 'Code AI',
    website_url: 'https://bito.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited requests' },
    features: ['Code generation', 'Explanations', 'IDE integration', 'Chat', 'Refactoring'],
    use_cases: ['Coding', 'Learning', 'Productivity'],
    tags: ['coding', 'ide', 'learning', 'productivity'],
  },
  {
    name: 'CodeRabbit',
    description: 'AI code review assistant for pull requests',
    category: 'Code AI',
    website_url: 'https://coderabbit.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited reviews' },
    features: ['Code review', 'PR comments', 'Security checks', 'Best practices', 'GitHub integration'],
    use_cases: ['Code review', 'Quality assurance', 'Security'],
    tags: ['coding', 'review', 'security', 'github'],
  },
  {
    name: 'Mintlify',
    description: 'AI-powered documentation generator for code',
    category: 'Code AI',
    website_url: 'https://mintlify.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$99', free_tier: 'Open source only' },
    features: ['Doc generation', 'Code comments', 'API docs', 'Beautiful docs', 'Auto-updates'],
    use_cases: ['Documentation', 'API docs', 'Code comments'],
    tags: ['documentation', 'api', 'docs', 'developer'],
  },
  {
    name: 'Codium',
    description: 'AI test generation tool that writes tests for your code',
    category: 'Code AI',
    website_url: 'https://codium.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$19', free_tier: 'Limited' },
    features: ['Test generation', 'Test suggestions', 'IDE integration', 'Multiple languages'],
    use_cases: ['Testing', 'Quality assurance', 'Development'],
    tags: ['testing', 'code', 'quality', 'developer'],
  },
  {
    name: 'DeepCode',
    description: 'AI-powered code review and security analysis',
    category: 'Code AI',
    website_url: 'https://snyk.io',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Custom', free_tier: 'Limited scans' },
    features: ['Code analysis', 'Security scanning', 'Vulnerability detection', 'CI/CD integration'],
    use_cases: ['Security', 'Code quality', 'Vulnerability scanning'],
    tags: ['security', 'code-analysis', 'vulnerabilities', 'ci-cd'],
  },

  // Additional Audio AI Tools
  {
    name: 'Uberduck',
    description: 'AI voice generation and cloning platform',
    category: 'Audio AI',
    website_url: 'https://uberduck.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Voice cloning', 'Text-to-speech', 'Voice library', 'API access', 'Rap generation'],
    use_cases: ['Voiceovers', 'Content creation', 'Entertainment', 'API integration'],
    tags: ['voice', 'tts', 'cloning', 'audio'],
  },
  {
    name: 'Murf',
    description: 'AI voice generator with 120+ voices in 20+ languages',
    category: 'Audio AI',
    website_url: 'https://murf.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$19', free_tier: '10 minutes' },
    features: ['120+ voices', 'Multi-language', 'Voice cloning', 'Voice changer', 'Studio quality'],
    use_cases: ['Voiceovers', 'Audiobooks', 'Podcasts', 'Content creation'],
    tags: ['voice', 'tts', 'multilingual', 'audio'],
  },
  {
    name: 'Speechify',
    description: 'AI text-to-speech tool for reading documents and web pages',
    category: 'Audio AI',
    website_url: 'https://speechify.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$11', free_tier: 'Limited' },
    features: ['Text-to-speech', 'Document reading', 'Browser extension', 'Mobile app', 'Multiple voices'],
    use_cases: ['Reading assistance', 'Accessibility', 'Learning', 'Productivity'],
    tags: ['tts', 'accessibility', 'reading', 'productivity'],
  },
  {
    name: 'Podcastle',
    description: 'AI-powered podcast creation and editing platform',
    category: 'Audio AI',
    website_url: 'https://podcastle.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited hours' },
    features: ['Podcast editing', 'AI voices', 'Transcription', 'Noise removal', 'Magic dust'],
    use_cases: ['Podcasts', 'Audio editing', 'Content creation'],
    tags: ['podcast', 'audio', 'editing', 'content'],
  },
  {
    name: 'AssemblyAI',
    description: 'AI audio transcription and understanding API',
    category: 'Audio AI',
    website_url: 'https://assemblyai.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Pay per minute', free_tier: '5 hours/month' },
    features: ['Transcription', 'Speaker diarization', 'Sentiment analysis', 'Entity detection', 'API'],
    use_cases: ['Transcription', 'Audio analysis', 'API integration'],
    tags: ['transcription', 'api', 'audio', 'developer'],
  },
  {
    name: 'Rev AI',
    description: 'AI transcription service with high accuracy',
    category: 'Audio AI',
    website_url: 'https://rev.com/ai',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$0.25/min', free_tier: 'No' },
    features: ['High accuracy', 'Fast turnaround', 'Multiple languages', 'API access', 'Human review'],
    use_cases: ['Transcription', 'Subtitles', 'Captions', 'API integration'],
    tags: ['transcription', 'accuracy', 'api', 'professional'],
  },
  {
    name: 'LALAL.AI',
    description: 'AI-powered audio separation tool for isolating vocals and instruments',
    category: 'Audio AI',
    website_url: 'https://lalal.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$15', free_tier: 'Limited minutes' },
    features: ['Vocal isolation', 'Instrument separation', 'Stem extraction', 'High quality'],
    use_cases: ['Music production', 'Karaoke', 'Remixing', 'Audio editing'],
    tags: ['audio', 'separation', 'music', 'editing'],
  },
  {
    name: 'Audo.ai',
    description: 'AI audio enhancement and noise removal tool',
    category: 'Audio AI',
    website_url: 'https://audo.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited minutes' },
    features: ['Noise removal', 'Audio enhancement', 'Background removal', 'Quality improvement'],
    use_cases: ['Audio cleaning', 'Podcast editing', 'Quality improvement'],
    tags: ['audio', 'enhancement', 'noise-removal', 'editing'],
  },

  // Additional Productivity AI Tools
  {
    name: 'ChatPDF',
    description: 'AI tool to chat with PDF documents and extract information',
    category: 'Productivity AI',
    website_url: 'https://chatpdf.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$5', free_tier: '3 PDFs/day' },
    features: ['PDF chat', 'Document Q&A', 'Multi-language', 'Citation', 'Large files'],
    use_cases: ['Document analysis', 'Research', 'Information extraction', 'Q&A'],
    tags: ['pdf', 'document', 'productivity', 'research'],
  },
  {
    name: 'Humata',
    description: 'AI research assistant for PDFs and documents',
    category: 'Productivity AI',
    website_url: 'https://humata.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$15', free_tier: '60 pages' },
    features: ['PDF analysis', 'Q&A', 'Summarization', 'Citation', 'Multiple files'],
    use_cases: ['Research', 'Document analysis', 'Information extraction'],
    tags: ['pdf', 'research', 'document', 'productivity'],
  },
  {
    name: 'TLDR This',
    description: 'AI tool to summarize articles, documents, and web pages',
    category: 'Productivity AI',
    website_url: 'https://tldrthis.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$4', free_tier: '10 summaries/month' },
    features: ['Article summarization', 'PDF summary', 'Key points', 'Browser extension'],
    use_cases: ['Reading', 'Research', 'Information extraction', 'Productivity'],
    tags: ['summarization', 'productivity', 'reading', 'research'],
  },
  {
    name: 'Genei',
    description: 'AI research tool for summarizing and organizing documents',
    category: 'Productivity AI',
    website_url: 'https://genei.io',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: 'Limited' },
    features: ['Document summarization', 'Research organization', 'Citation', 'Note-taking'],
    use_cases: ['Research', 'Academic work', 'Document organization'],
    tags: ['research', 'summarization', 'academic', 'productivity'],
  },
  {
    name: 'Consensus',
    description: 'AI research tool that finds and summarizes scientific papers',
    category: 'Productivity AI',
    website_url: 'https://consensus.app',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: 'Limited queries' },
    features: ['Paper search', 'Summarization', 'Citations', 'Evidence-based', 'Academic'],
    use_cases: ['Research', 'Academic work', 'Evidence gathering'],
    tags: ['research', 'academic', 'papers', 'evidence'],
  },
  {
    name: 'Elicit',
    description: 'AI research assistant for finding and analyzing research papers',
    category: 'Productivity AI',
    website_url: 'https://elicit.org',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited queries' },
    features: ['Paper search', 'Extraction', 'Summarization', 'Synthesis', 'Academic'],
    use_cases: ['Research', 'Literature review', 'Academic work'],
    tags: ['research', 'academic', 'papers', 'synthesis'],
  },
  {
    name: 'SciSpace',
    description: 'AI research assistant for reading and understanding scientific papers',
    category: 'Productivity AI',
    website_url: 'https://typeset.io',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$8', free_tier: 'Limited' },
    features: ['Paper reading', 'Q&A', 'Citation', 'Summarization', 'Academic'],
    use_cases: ['Research', 'Paper reading', 'Academic work'],
    tags: ['research', 'academic', 'papers', 'reading'],
  },
  {
    name: 'Scholarcy',
    description: 'AI tool for summarizing research papers and articles',
    category: 'Productivity AI',
    website_url: 'https://scholarcy.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$5', free_tier: 'Limited' },
    features: ['Paper summarization', 'Key points', 'Citation extraction', 'Flashcards'],
    use_cases: ['Research', 'Academic work', 'Learning'],
    tags: ['research', 'academic', 'summarization', 'learning'],
  },
  {
    name: 'QuillBot',
    description: 'AI writing assistant for paraphrasing, summarizing, and grammar checking',
    category: 'Productivity AI',
    website_url: 'https://quillbot.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited words' },
    features: ['Paraphrasing', 'Summarization', 'Grammar check', 'Citation', 'Translator'],
    use_cases: ['Writing', 'Editing', 'Academic writing', 'Content creation'],
    tags: ['writing', 'paraphrasing', 'grammar', 'productivity'],
  },
  {
    name: 'Wordtune',
    description: 'AI writing assistant for improving and rewriting text',
    category: 'Productivity AI',
    website_url: 'https://wordtune.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited rewrites' },
    features: ['Text rewriting', 'Tone adjustment', 'Grammar check', 'Browser extension', 'Summarization'],
    use_cases: ['Writing improvement', 'Email', 'Content', 'Editing'],
    tags: ['writing', 'rewriting', 'productivity', 'editing'],
  },
  {
    name: 'DeepL',
    description: 'AI translation tool with high accuracy and natural translations',
    category: 'Productivity AI',
    website_url: 'https://deepl.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$7', free_tier: '500K characters/month' },
    features: ['Translation', 'High accuracy', '30+ languages', 'Natural translations', 'Document translation'],
    use_cases: ['Translation', 'Multilingual content', 'Communication'],
    tags: ['translation', 'multilingual', 'productivity', 'communication'],
  },
  {
    name: 'Loom',
    description: 'Video messaging tool with AI transcription and summaries',
    category: 'Productivity AI',
    website_url: 'https://loom.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$8', free_tier: '25 videos' },
    features: ['Screen recording', 'Video messages', 'Transcription', 'AI summaries', 'Sharing'],
    use_cases: ['Communication', 'Tutorials', 'Feedback', 'Documentation'],
    tags: ['video', 'communication', 'productivity', 'recording'],
  },
  {
    name: 'Tavily',
    description: 'AI research assistant that searches and synthesizes web information',
    category: 'Productivity AI',
    website_url: 'https://tavily.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited queries' },
    features: ['Web search', 'Information synthesis', 'API access', 'Real-time data', 'Citations'],
    use_cases: ['Research', 'Information gathering', 'Fact-checking', 'Content creation'],
    tags: ['research', 'search', 'productivity', 'api'],
  },
  {
    name: 'Krisp',
    description: 'AI-powered noise cancellation for calls and meetings',
    category: 'Productivity AI',
    website_url: 'https://krisp.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$8', free_tier: '60 minutes/week' },
    features: ['Noise cancellation', 'Echo removal', 'Background noise', 'Works with any app'],
    use_cases: ['Meetings', 'Calls', 'Recording', 'Productivity'],
    tags: ['audio', 'noise-cancellation', 'meetings', 'productivity'],
  },
  {
    name: 'Calendly',
    description: 'Scheduling tool with AI features for meeting coordination',
    category: 'Productivity AI',
    website_url: 'https://calendly.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: '1 event type' },
    features: ['Scheduling', 'Calendar sync', 'Reminders', 'Integrations', 'Team features'],
    use_cases: ['Scheduling', 'Meeting coordination', 'Appointments'],
    tags: ['scheduling', 'calendar', 'productivity', 'meetings'],
  },
  {
    name: 'Clockwise',
    description: 'AI calendar assistant that optimizes your schedule automatically',
    category: 'Productivity AI',
    website_url: 'https://clockwise.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$7', free_tier: 'Limited' },
    features: ['Auto-scheduling', 'Focus time', 'Meeting optimization', 'Calendar sync'],
    use_cases: ['Time management', 'Scheduling', 'Productivity', 'Focus'],
    tags: ['calendar', 'scheduling', 'productivity', 'time-management'],
  },
];

